### ISSUE TITLE
Write Permission?

### ISSUE THREAD

**Issue by Shamshiel** [antonpup/Dota2GSI#1]
Are you planning to give other people permission to create branches?
I really would like to contribute but right now it is not possible to create a branch for a new feature.

**Comment by Andrew229** [comment]
Thanks for your interest in the project! You can contribute code without write permissions to the main repository. Just fork the repository, write your code, and then make a pull request to my repository, and then we take it from there. Steps detailed [here.](http://stackoverflow.com/questions/6286571/are-git-forks-actually-git-clones/6286877#6286877)

Note that I neglected to handle all of the project dependencies, so it might be a huge hassle getting everything running. I'm in the process of setting the project up with Maven to make it easier to build/modify. 

If you'd like to work on something immediately, you'll need the following libraries.
Clarity - https://github.com/skadistats/clarity
JsonSmart2 - https://github.com/netplex/json-smart-v2

**Comment by antonpup** [comment]
You can fork this repo and create a branch on your fork. After you are done with your features, you can make a pull request.
