### ISSUE TITLE
(Solved) Installed tried . Dota 2 not sending info to the exemple provided

### ISSUE THREAD

**Issue by gentmat** [antonpup/Dota2GSI#10]
I checked our the folder location and the extension hidden nothing worked . I am pretty sure there
is something wrong and dota is unable to send info !
Anyone can confirm if it is still active or not >?

**Comment by antonpup** [comment]
Works fine for me

**Comment by antonpup** [comment]
What is the path you are putting the cfg file into?

**Comment by gentmat** [comment]
Works now ! There was 2 path with the same integration folder ! that made the issue and both are for dota .  i dont know the reason for that . finally i saw it by searching the pc ! 
issue fixed thank you bro

**Comment by antonpup** [comment]
Glad to hear that you solved it! :)

**Comment by gentmat** [comment]
Thank you . 
I wonder 2 questions :
1-How can we retreive our hero buffs (lets say i activated drums ) or an aura buff
2- im new to c# its not my language . How can we print the data raw (all data) so in case there is smth missing (information gamestate gives us that you did not parse) we do ot ourself . Is that easy to be done ?

**Comment by gentmat** [comment]
Information about our hero i dont care what other hero doing (just to make that clear for people who flames dorectly and think of bots) 
Im trying to make led integration with my game aurora github is too complicated and i think this library very clean to customize what you looking for
