### ISSUE TITLE
NuGet package is missing the 'added' gamestate

### ISSUE THREAD

**Issue by JoniSykes** [antonpup/Dota2GSI#12]
Title speaks for itself.

**Comment by antonpup** [comment]
It's missing the "added" because Dota 2 reports it as garbage. Instead of values, it just states true or false. Thus it was excluded.

**Comment by JoniSykes** [comment]
Thanks for the update :)
Any reason that this basic program wouldn't work since removing the 'added' api call:
```
    class Program
    {
        static void Main(string[] args)
        {
            //create game state listener with port 4000
            GameStateListener gsl = new GameStateListener(4000);
            //register handler method
            gsl.NewGameState += new NewGameStateHandler(OnNewGameState);

            gsl.Start();

            //If all is running smoothly:
            Console.WriteLine("Listening for game integration calls...");
        }

        //handler method
        static void OnNewGameState(GameState gs)
        {
            //do stuff
            Console.WriteLine("Hi");
        }
    }
```
It's just exiting as soon as it's run....

I'm new to C#, I usually work in NodeJS.
Any chance there's such a thing as reaching the 'end' of main and just exiting, since exiting by code zero sounds healthy, not an error. Should there be some kind of 'while' in here or a wait for input of some kind?

**Comment by antonpup** [comment]
It exits because it reaches the end of Main() and thus terminates.

That example wasn't really supposed to be 100% functional, just a code reference. Try the provided example program: https://github.com/antonpup/Dota2GSI/tree/master/Dota2GSI%20Example%20program

**Comment by JoniSykes** [comment]
Funny you mentioned that ;)
I just tried it (sort of):
```
    class Program
    {
        static void Main(string[] args)
        {
            //create game state listener with port 4000
            GameStateListener gsl = new GameStateListener(4000);
            //register handler method
            gsl.NewGameState += new NewGameStateHandler(OnNewGameState);

            gsl.Start();

            do
            {
                while (!Console.KeyAvailable)
                {
                    Thread.Sleep(1000);
                }
            } while (Console.ReadKey(true).Key != ConsoleKey.Escape);

            //If all is running smoothly:
            Console.WriteLine("Listening for game integration calls...");
        }

        //handler method
        static void OnNewGameState(GameState gs)
        {
            //do stuff
            Console.WriteLine("Hi");
        }
    }
```
This gets 'stuck' in the loop and never breaks out to the handler.
I take you were able to work locally with this, do you have a working version I could reference?

Thanks for the reply :)

**Comment by antonpup** [comment]
My other project relies on a slightly modified version of this.
https://github.com/antonpup/Aurora

It's functional, the only issue that I know of is cooldowns not working since 7.00. But it's an issue on Valve's end. Game reports 0 regardless of the actual cooldown.

https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/Dota%202/GSI/GameState_Dota2.cs

**Comment by JoniSykes** [comment]
Let me take a look. 
For anyone else venturing this way, wanna put a quick note in the readme about what we've discussed?
Or I can raise a PR for it if that helps you?
Thanks for the great work!

**Comment by JoniSykes** [comment]
That is one HELL of a project, nice work. Why does this not come up in google when I've been searching for 'Dota GSI Chroma' for the last two days.

**Comment by antonpup** [comment]
Well... no note is needed about "added"? Because it doesn't exist in the documentation for this to begin with. But one of these days I will write proper example programs. But not today.

If you wanna do that, go ahead, I'll accept PR.

**Comment by JoniSykes** [comment]
Thanks bro. 

'Added' is used in the example program (the one in the folder, not the readme).
I'm not confident I need to change anything here any more since I wouldn't know what will produce a working example anyway. I'll just update the readme to make it clear(er) it's reference code not working code.

Now for another noob Q before I close this issue you've resolved so expertly:
What do I need from your other project to start writing effects for certain hero item casts/ability casts etc?
I want to work on Dota effects and I'm interested in eg: Morphling waveform or eg: any hero casting dagon. Stuff like that.

I'd prefer to contribute to yours as opposed to re-making what you've done so much on already.
I'll get downloading and looking over the files to see if I can find your effects before you reply :)

**Comment by antonpup** [comment]
For hero ability effects, take a look at this class: https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/Dota%202/Layers/Dota2HeroAbiltiyEffectsLayerHandler.cs
