### ISSUE TITLE
OnNewGameState(GameState gs)

### ISSUE THREAD

**Issue by gentmat** [antonpup/Dota2GSI#14]
Dota seems to send new information at avg 300 - 500 ms . that is cause of delay.
                    "\"Dota 2 Integration Configuration\"",
                    "{",
                    "    \"uri\"           \"http://localhost:80/\"",
                    "    \"timeout\"       \"5.0\"",
                    "    \"buffer\"        \"100\"",
                    "    \"throttle\"      \"0.01\"",
                    "    \"heartbeat\"     \"0.01\"",
                    "    \"data\"",
                    "    {",
                    "        \"provider\"      \"0\"",
                    "        \"map\"           \"0\"",
                    "        \"player\"        \"0\"",
                    "        \"hero\"          \"0\"",
                    "        \"abilities\"     \"1\"",
                    "        \"items\"         \"1\"",
                    "    }",
                    "}",
are these settings tweak able ? there is no documentation for these settings . How can i make the gs to update as fast as possible ? 
Thank you

**Comment by antonpup** [comment]
More information on GSI config can be found here: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration

Here's a config that I use for my other project, [Aurora](https://github.com/antonpup/Aurora): https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/Dota%202/GSI/gamestate_integration_aurora.cfg

Take a look at these, this should fix your problem.
