### ISSUE TITLE
Dota 2 GSI Not Working

### ISSUE THREAD

**Issue by jlfalcon3589** [antonpup/Dota2GSI#17]
Someone is running the Dota 2 GSI I am using a 7.06E version and it does not work for me I have the configuration file in the following path some_path/game\dota\cfg\gamestate_integration/gamestate_integration_testGSI.cfg but when I run the console application it does not come any results, how can I verify that the dota is actually sent data to the program, some way to check the sending of data from the client to the console application ??

**Comment by antonpup** [comment]
Seems to function properly on my end.
![http://i.imgur.com/A8DEqoW.png](https://i.imgur.com/A8DEqoW.png)

I did notice that when I started my example app first, and then dota, it didn't work. I then restarted the example app while in dota, and it was working fine.

**Comment by joelwurtz** [comment]
Run into the same problem, in fact it does not work when creating a local server, only works when creating a server hosted on a valve infrastructure it seems
