### ISSUE TITLE
Missing DOTA_Gamestate value

### ISSUE THREAD

**Issue by patchandthat** [antonpup/Dota2GSI#2]
There's a value missing for when you're loading into a custom game, which throws when trying to parse into DOTA_GameState.

`DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP`

I'd send you a pull request, but I've also taken the liberty of introducing some interfaces and refactoring the thread/IAsyncResult stuff into TPL.  Let me know if you want a PR.

**Comment by antonpup** [comment]
Included in [V1.0.3](https://github.com/antonpup/Dota2GSI/releases/tag/v1.0.3) along with other fixes. Thank you.
