### ISSUE TITLE
Please Read this

### ISSUE THREAD

**Issue by Hackerprod** [antonpup/Dota2GSI#20]
Hello antonpup friend, there is some way to get the data of the other players (Radiant and Dire) as a spectator mode. regards

**Comment by Nilceps** [comment]
https://github.com/simon-wh/Dota2GSI check out his fork

**Comment by Hackerprod** [comment]
Hello brother ... thanks for your help. regards

**Comment by antonpup** [comment]
Better support for team data has been added to the latest release.
