### ISSUE TITLE
Buffs and courier items

### ISSUE THREAD

**Issue by KNOWPEIN** [antonpup/Dota2GSI#24]
Thanks for this great project....

I have few questions

does GSI provide items on courier(as of now i am unable to find)....

does GSI provide buffs applied to heroes (unable to find this too)

any help would be much appreciated

**Comment by kkimmikko** [comment]
Did u find any info about it? Can't find anything related to that..

**Comment by antonpup** [comment]
GSI does offer courier information, not sure if it is available only to spectators.

Sample data:
```
"courier5": {
      "health": 6,
      "max_health": 6,
      "alive": true,
      "respawn_time_remaining": 0,
      "xpos": 6324,
      "ypos": 6166,
      "yaw": 212,
      "owner": 3,
      "flying_upgrade": true,
      "shield": false,
      "boost": false,
      "items": {
        "item0": {
          "owner": 3,
          "name": "item_ward_sentry"
        }
      }
    }
```

**Comment by antonpup** [comment]
Courier items support has been added to the latest release.
