### ISSUE TITLE
Captains Mode Ban-Pick

### ISSUE THREAD

**Issue by GoranKovac** [antonpup/Dota2GSI#25]
Is it possible to get GSI info on this?
Team Hero Pick
Team Hero Ban

**Comment by GoranKovac** [comment]
Implemented by my self

**Comment by webmilio** [comment]
Since this repo is dead as hell, please share yours @GoranKovac.

**Comment by antonpup** [comment]
I know this was closed. But in a recent update `2.0.0`, this was implemented.
