### ISSUE TITLE
Is this supported with .net 6 or 7?

### ISSUE THREAD

**Issue by ErNoI** [antonpup/Dota2GSI#26]
Im wondering if this still works and if it works with the newer versions of .net? has anyone tried it? is there any known issues?

**Comment by su1cidal** [comment]
Hi, it still works, six months ago I created an application based on it and WPF.  You can check it below:
  https://github.com/su1cidal/DotaVinci/releases

The main problem for me is that it doesn't support events like: killing Roshan, first blood, etc., or I didn't find it😔

**Comment by ErNoI** [comment]
Yeah I'm trying it it out atm. Someone added updates to the repository recently with new stuff. But its not included in the package. So I just made my own reference to the project for now.  There is a Roshan-state but it seems like its not available during a real game. Some stuff are only available as spectator.

**Comment by antonpup** [comment]
I know this was closed. But version `2.0.1` was upgraded to .NET 8.0.
