### ISSUE TITLE
How to track Roshan?

### ISSUE THREAD

**Issue by Chrompower** [antonpup/Dota2GSI#28]
I can't find a way to track roshan-kills. Anyone got an idea?

**Comment by antonpup** [comment]
I don't think GSI exposes Roshan kills specifically.
As a spectator GSI exposes `RoshanState` and `RoshanStateEndTime` in [Map.cs](https://github.com/antonpup/Dota2GSI/blob/master/Dota2GSI/Dota2GSI/Nodes/Map.cs#L189) which can be used to determine when Roshan is alive or dead. Otherwise, this information is not available during the game.

**Comment by antonpup** [comment]
Actually, upon closer inspection there is data for roshan. It wasn't available when I wrote this library. Not sure if this is only available to spectators or not.

Sample data:
```
"roshan": {
    "health": 6000,
    "max_health": 6000,
    "alive": true,
    "spawn_phase": 0,
    "phase_time_remaining": 0,
    "xpos": -6398,
    "ypos": 7560,
    "yaw": 357,
    "items_drop": {
      "item0": "item_aegis"
    }
  }
```

**Comment by su1cidal** [comment]
These guys **dotabod com** somehow track roshan.

**Comment by antonpup** [comment]
When the player has vision of Roshan, you can get information from the `minimap` provider. But other than that, you cannot get other Roshan information when playing the game.

Sample data:
```
"o109": {
      "xpos": -7808,
      "ypos": 7680,
      "image": "minimap_creep",
      "team": 4,
      "yaw": 347,
      "unitname": "npc_dota_roshan",
      "visionrange": 1400
    }
```

**Comment by Chrompower** [comment]
Thank you for the responses.

I think there is a data category in the cfg file that is missing.
It's called "events". If I read it correctly the specific event is called "roshan_killed". There are also more, like "aegis_picked_up" or "aegis_denied".  See: https://github.com/dotabod/backend/blob/master/packages/dota/src/types.ts#L341

I am a really bad programmer but I think just adding the "events" in the cfg file does not help, it also needs to be included in the library, right?

**Comment by antonpup** [comment]
Yes, you are correct. The `events` provider does show events for Roshan kills among others. And seems to be available during both play and spectating.

Sample data:
```
"events": [
    {
      "game_time": 2490,
      "event_type": "aegis_picked_up",
      "player_id": 0,
      "snatched": false
    },
    {
      "game_time": 2489,
      "event_type": "roshan_killed",
      "killed_by_team": "radiant",
      "killer_player_id": 2
    }
]
```

**Comment by antonpup** [comment]
In a future update of `Dota2GSI` you will be able to access event information to get Roshan kill information.

https://github.com/antonpup/Dota2GSI/blob/master/Dota2GSI/Dota2GSI/Nodes/Event.cs

**Comment by su1cidal** [comment]
Good job, mate

**Comment by antonpup** [comment]
Please take a look into `Events` in the latest release.

**Comment by Chrompower** [comment]
Unfortunately I can't make it work. I basically copy-pasted your code. Things like Hero Health or Talent Tree do get printed in the console. But when it comes to events nothing gets printed. 

As I see you already implemented the code:

```c#
            foreach (var game_event in gs.Events)
            {
                if (game_event.EventType == Dota2GSI.Nodes.EventsProvider.EventType.Bounty_rune_pickup)
                {
                    Console.WriteLine("Bounty rune was picked up!");
                    break;
                }
                else if (game_event.EventType == Dota2GSI.Nodes.EventsProvider.EventType.Roshan_killed)
                {
                    Console.WriteLine("Roshan was brutally killed!");
                    break;
                }
            }
``` 

But if I kill Roshan, or pick up a bounty rune, nothing gets printed.

I would appreciate help. Tried to solve it by myself for 2 hours with no success.

**Comment by antonpup** [comment]
Have you added `"Events" "1"` into your integration cfg file?

**Comment by Chrompower** [comment]
Yes, the cfg file was created by your function CreateGsifile()and I also checked it manually. 
I was testing it in a custom lobby – I can try it in a real game but I don't think it will make a difference. All the other data gets printed with no problem. But picking up a bounty rune or killing roshan does not print "Roshan was brutally killed!" or "Bounty rune was picked up!"

**Comment by antonpup** [comment]
There was a bug with parsing `Events`. Will push an update later. For now, if you want to test locally, this is the fix: 3e99adc41b987cca25a7efb7f7a70d32ab9d6a30

**Comment by antonpup** [comment]
If you don't want to build Dota2GSI locally, you can use artifacts from this build to link against, https://github.com/antonpup/Dota2GSI/actions/runs/7532700577

**Comment by Chrompower** [comment]
Thank you! I don't know how to fix it manually, so I will wait for the update.
