### ISSUE TITLE
Enum PlayerTeam missing value Spectator

### ISSUE THREAD

**Issue by patchandthat** [antonpup/Dota2GSI#3]
As titled, had an exception thrown as a game was loading, presumably before teams were assigned.

**Comment by antonpup** [comment]
Will add, I've also been having other issues. If you want to add me on steam to suggest improvements/fixes to me directly, feel free to do so. [http://steamcommunity.com/id/pupant/](My steam profile)/

**Comment by antonpup** [comment]
Closed due to inactivity.
