### ISSUE TITLE
Capture chat messages

### ISSUE THREAD

**Issue by Un1xCr3wR0x** [antonpup/Dota2GSI#30]
thanks a lot for sharing this , does it support capturing chat ?

**Comment by antonpup** [comment]
No, chat is not part of Game State Integration. I had a personal project for CSGO that read console, but in CS2 it's not easily doable. It can be done, but it's a janky solution.

If there is a way to read the console in Dota 2, this can be added.

**Comment by antonpup** [comment]
I investigated this, having access to Dota's console does not allow access to the chat messages. They aren't printed in the console. On the other hand, chat messages do get printed in Counter-Strike 2's console.

Unless there is a way to get Dota 2 to print chat messages in console, there isn't a safe way to read chat messages.

After doing research, there are other projects that translate Dota 2 chat messages using methods ranging from screen text recognition to dll injection (https://github.com/WatcherApps/GameChatTranslator, https://github.com/patriksletmo/Dota2Translator, https://github.com/ur0/DotATranslator). I wouldn't trust dll injection out of risking potentially banning Dota2GSI's users. And screen text recognition is a heavy operation and is outside the scope of this project.
