### ISSUE TITLE
Help infinity Listening for game integration calls...

### ISSUE THREAD

**Issue by BlackBro12** [antonpup/Dota2GSI#32]
I decided to run a test program, and there was such an endless loading, what should I do?

![image](https://github.com/antonpup/Dota2GSI/assets/155241338/2fcbe067-9277-42ce-8554-20fedad1b6f4)
![image](https://github.com/antonpup/Dota2GSI/assets/155241338/6d5aafd6-8d27-4a4b-a336-d4dc5066dbde)
![image](https://github.com/antonpup/Dota2GSI/assets/155241338/a689d5fa-c746-4237-9dd4-4cb3bd7bf9f0)

**Comment by antonpup** [comment]
Have you restarted Dota 2 after creating the .cfg file? Dota 2 detects new gsi config files on launch.

**Comment by BlackBro12** [comment]
yes, I restarted Dota and the computer and the program, still an error, can we go to discord or another social network where they could help me please?

**Comment by BlackBro12** [comment]
https://youtu.be/k5LvveWqV44 - in this video I showed the code, launch and availability of cfg

**Comment by antonpup** [comment]
In your cfg file your specified port is `3000`, but in your example program the specified port is `4000`. Change the port in your cfg file to `4000` and everything should work.

**Comment by antonpup** [comment]
If you use the [latest release](https://github.com/antonpup/Dota2GSI/releases/latest), it adds automatic GSI config file generation. That should resolve your issue as well.
