### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by BlackBro12** [antonpup/Dota2GSI#35]
![image](https://github.com/antonpup/Dota2GSI/assets/155241338/c8a970d9-e3fe-4c30-8af2-b54bc58a00a4)
How to fix it?

**Comment by antonpup** [comment]
You have to build the solution using cmake. Follow instructions in [the readme](https://github.com/antonpup/Dota2GSI?tab=readme-ov-file#building-dota-2-gsi).
