### ISSUE TITLE
Getting the rest of the Players IDs in the game

### ISSUE THREAD

**Issue by btagliani** [antonpup/Dota2GSI#4]
As the title says, is it possible to get the ID of the players in the match?

**Comment by eVen-gits** [comment]
It's possible to read that from server.log file afaik. Not sure if relevant here.

**Comment by antonpup** [comment]
GSI only provides information about the local hero/player.

**Comment by eVen-gits** [comment]
@ReinventingHell if it's not supported by the Dota2GSI, you can pull it from server_log.txt.

The lines will look like this:

`03/08/2016 - 18:05:52: =[A:1:571956233:6477] (Lobby 24450769683518156 DOTA_GAMEMODE_CM 0:[U:1:148900451] 1:[U:1:113835565] 2:[U:1:145630550] 3:[U:1:109595467] 4:[U:1:106488637] 5:[U:1:103349197] 6:[U:1:97779707] 7:[U:1:12420706] 8:[U:1:71591350] 9:[U:1:95251565]) (Party 24450769661428113 0:[U:1:103349197] 1:[U:1:97779707] 2:[U:1:12420706] 3:[U:1:71591350] 4:[U:1:95251565])
03/08/2016 - 18:48:51: loopback (Party 24450769661428113 0:[U:1:103349197] 1:[U:1:97779707] 2:[U:1:12420706] 3:[U:1:71591350] 4:[U:1:95251565])
03/08/2016 - 18:57:50: =[A:1:589256704:6477] (Lobby 24450769736353929 DOTA_GAMEMODE_ALL_DRAFT 0:[U:1:154362605] 1:[U:1:131230373] 2:[U:1:39901779] 3:[U:1:102300672] 4:[U:1:128806974] 5:[U:1:118265470] 6:[U:1:117643620] 7:[U:1:88435449] 8:[U:1:95251565] 9:[U:1:169011674]) (Party 24450769733052342 0:[U:1:95251565])
03/08/2016 - 19:24:48: loopback (Party 24450769733052342 0:[U:1:95251565])
03/08/2016 - 21:08:21: =[A:1:3416006662:6477] (Lobby 24450769821083406 DOTA_GAMEMODE_CM 0:[U:1:86824871] 1:[U:1:103032016] 2:[U:1:77287764] 3:[U:1:93115341] 4:[U:1:78512097] 5:[U:1:105639972] 6:[U:1:95251565] 7:[U:1:86834305] 8:[U:1:113215577] 9:[U:1:168600255]) (Party 24450769733052342 0:[U:1:95251565])
03/08/2016 - 21:37:32: loopback (Party 24450769733052342 0:[U:1:95251565])
03/08/2016 - 21:40:26: 146.66.159.192:27054 (Lobby 24450769869850317 DOTA_GAMEMODE_CM 0:[U:1:86824871] 1:[U:1:103032016] 2:[U:1:77287764] 3:[U:1:168600255] 4:[U:1:95251565] 5:[U:1:101220507] 6:[U:1:107023378] 7:[U:1:90324740] 8:[U:1:116881520] 9:[U:1:114844288]) (Party 24450769733052342 0:[U:1:95251565])
03/08/2016 - 22:22:58: loopback (Lobby 24450769869850317 DOTA_GAMEMODE_CM 0:[U:1:86824871] 1:[U:1:103032016] 2:[U:1:77287764] 3:[U:1:168600255] 4:[U:1:95251565] 5:[U:1:101220507] 6:[U:1:107023378] 7:[U:1:90324740] 8:[U:1:116881520] 9:[U:1:114844288]) (Party 24450769733052342 0:[U:1:95251565])
03/09/2016 - 10:34:20: loopback
03/09/2016 - 10:56:46: 146.66.153.39:28062
03/09/2016 - 11:12:22: loopback
03/09/2016 - 11:21:58: 146.66.153.202:28030
03/09/2016 - 11:36:22: loopback
03/09/2016 - 11:42:30: =[A:1:3926731784:6478] (Lobby 24452512909531070 DOTA_GAMEMODE_AP 0:[U:1:207009345] 1:[U:1:113688158] 2:[U:1:211939818] 3:[U:1:272583600] 4:[U:1:327435620] 5:[U:1:39401836] 6:[U:1:256173771] 7:[U:1:329508438] 8:[U:1:302226646] 9:[U:1:95251565]) (Party 24452512903951892 0:[U:1:95251565])
03/09/2016 - 12:31:34: loopback (Party 24452512903951892 0:[U:1:95251565])`

As you can see, those are IDs from users that are in game. I think that should help you out with whatever you are doing. The file is usually located in

`C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota`

**Comment by btagliani** [comment]
@EgejVencelj Thanks, this looks useful actually! Im trying to do an app that get the players IDs as soon as you connect to the server, and show if you had any games with them before, and whats the winrate with them.

**Comment by eVen-gits** [comment]
@ReinventingHell feel free to take a look at [my project](https://github.com/EgejVencelj/PlayerScout) then. It's a rough workframe for that, and I haven't done anything in a while, but it should provide you that functionality - feel free to take whatever you want :+1:

**Comment by btagliani** [comment]
@EgejVencelj Do you know if Dota still uses server_log.txt? I think it doesnt anymore, right?

**Comment by eVen-gits** [comment]
@ReinventingHell it still does, I think.

**Comment by btagliani** [comment]
@EgejVencelj The last lines it had were from a few weeks ago, and I have played a lot since then. Also, I deleted it to see if Dota recreated it and nothing.

**Comment by moonrobin** [comment]
@ReinventingHell Any luck getting some form of this to work?

**Comment by dengxiangcheng** [comment]
Can GSI  provides information about all players for LAN'S?

**Comment by dengxiangcheng** [comment]
@antonpup Can GSI provides information about all players for LAN'S?

**Comment by antonpup** [comment]
For a LAN, you can set up every client to send his information to one address. That way, all clients report to one computer and you can gather information about everyone that way.

If you want information about other players, like who are not local to your network, you won't be able to unless you set up a way for them to report that his data to you.

**Comment by dengxiangcheng** [comment]
@antonpup 
I don't know how can set up every client to send his information to one address?
if i am a observer at room ,how can i set up it ?

**Comment by joelwurtz** [comment]
Just want to make a follow up, maybe it was updated, but you can have all players informations if you are a spectator of the game (using dota tv)
