### ISSUE TITLE
Cant take any game status from listener.

### ISSUE THREAD

**Issue by achooley** [antonpup/Dota2GSI#5]
I try use example project. An result 0. Zero callback in console. Can some one help me?

**Comment by antonpup** [comment]
Did you copy the cfg file to enable GSI?

**Comment by achooley** [comment]
solved problem. Wrong path. One more question. Can listener return game UI state? Like - callback when game ready. From ingame console:

> ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME

**Comment by antonpup** [comment]
I don't think GSI itself provides such information. But if someone wants to fork the repo and add support for reading Dota's log/console files. Feel free to do so.

**Comment by Thorvaldd** [comment]
Hi. I'm having trouble to receiving game statuses. Maybe i doing something wrong. I'll be glad if you guide me. So i created cfg file with such uri -> "http://localhost:4000/ ".
I launch game in play with bots mode, and nothing happened.Perhaps I have misunderstood something?

**Comment by Thorvaldd** [comment]
Omg, i put cfg in wrong path. Now it's okay.

**Comment by sheldonj** [comment]
Can someone reconfirm the full path for the config file. I'm pretty sure the path listed in the readme file is wrong as that isn't a valid path for Reborn. (Am I wrong?)

**Comment by antonpup** [comment]
@sheldonj The path is correct. Official logitech integration uses that path, as well as PlaysTV.

![http://puu.sh/q0EJz/be95c9c404.png](http://puu.sh/q0EJz/be95c9c404.png)

**Comment by Thorvaldd** [comment]
@sheldonj Double check your directory name for typo, cause i'm stuck on same (i think same)problem.
![image](https://cloud.githubusercontent.com/assets/6178958/16819530/8aac7cb6-4955-11e6-8b6e-a5b1169ba5ca.png)

**Comment by sheldonj** [comment]
Thanks guys, at work right now but will check.

**Comment by sheldonj** [comment]
I definetly have the config in the correct place, I can test my endpoint for receiving posts no problem and thats work.  Just not seeing any posts from Dota2, nor do I see any gamestate configs loaded in the console. I wonder what else it could be.

**Comment by antonpup** [comment]
Run your program as Admin, it might not be able to create network listener.

**Comment by sheldonj** [comment]
Im not having any issues receiving network requests. I can send requests to the endpoint with Postman and it works just fine. it just seems that Dota2 client isn't actually sending the requests. When you launch the game do you see any thing in the Dota2 console about your gamestate_integration loading?

**Comment by Thorvaldd** [comment]
@sheldonj it little bit weird. But i still think that you something missed in config. If you don't see any requests from D2 it could be problem in config file, directory placement/namin or mby wrong Uri for listening game states. Also check Uri in your program and cfg file.

**Comment by antonpup** [comment]
Make sure your .cfg file complies with the requirements listed for CSGO.

[https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration)

**Comment by sheldonj** [comment]
I ended up figuring it out, totally rookie mistake. I had just reinstalled a new computer (and I hadn't turned show file extensions on. So I was creating the config file with a .cfg.txt file extension by mistake, sorry for wasting everyone's time.

**Comment by achooley** [comment]
Hi there. Can someone confirm correct work with latest patch?

**Comment by antonpup** [comment]
I played the game today with my [keyboard lighting utility](https://github.com/antonpup/Aurora). It was operating just fine.

**Comment by achooley** [comment]
@antonpup  can you pls check *.cfg file path

**Comment by antonpup** [comment]
The .cfg path did not change.
